---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pl-stan
spec:
  replicas: 2
  volumeClaimTemplates:
  - metadata:
      name: stan-sts-vol
    spec:
      storageClassName: alibabacloud-cnfs-nas
      accessModes:
      - ReadWriteOnce
      volumeMode: "Filesystem"
      resources:
        requests:
          storage: 1Gi
