---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: alibabacloud-cnfs-nas
  resources:
    requests:
      storage: 500M
